os: osx

language: objective-c

git:
  depth: 5

env:
  global:
    - secure: "pv1clfyko3JMmlllWFSqv0oBqIGJA9eGVtizXQoY2q8t6se9FvOttSL39pydkFPcmAWuvesceQV38zyinV9Y+Yk5RhLt2T7P1C7yjL5igO5KI1VvQOnUEOCy/1IIOdTFjmCu+vl0iZlDGJdO3nGVev4IKMnqru2dWQKsH+0wqVrakFxRflfGv3jsB/UCNUmCWCzyAGMWtmNGbA9gmL0nlbGUHBlxz7ETDX7NY+iG/7WMW+SOkw4B2UgkCCyGlrb0660b/0CFyHoDZQu3xnCns0hsosvSwwaqqNkf/WgtwHbrpLkJW73euA3oy2rBrYO3YfJpWpmVtgxZASvBQodNh3jaD9iRSA1b3W0fmChk/8Ar/LU+HL7BA/M9tdRA+43s+aGLL/vHO8N/sAFIr1Bz5ipGqK0OIH4OhIl847I55CRN+CMhZ2agaAHqK2lZGX6+F4NNnQGQ7PRwTllLt1703MHGNGCAPFgm58nxlbrhMxVJsHz6YYQKvO8vzFgpU6vFblSvFefg00M3pINB1szd9rlKux5kyKwtaM0RPP2/wvQQRPwZCYd+VJIgf2f8uxAxVYQNgo4DSrRz1K8tg7UIfsOIyw0oqG2JkDxNAQd/msXvm0uUGDJHG//nj/lEFnWRmELk8+cymAb6dHARDoi1FLbVjuXXo57gxCYx2PN6Rbc="
  matrix:
    - NODE_VERSION="0.10.36"
    - NODE_VERSION="0.12.7"
    - NODE_VERSION="4.0.0"
    - NODE_VERSION="5.1.0"

install:
  - rm -rf ~/.nvm
  - git clone https://github.com/creationix/nvm.git ~/.nvm
  - source ~/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - node -v
  - npm -v
  - npm install

script:
  - mkdir /Users/travis/build/tmarrinan/Build
  - cd ..
  - tar czf /Users/travis/build/tmarrinan/Build/websocketio_mac_${NODE_VERSION}.tar.gz websocketio
  - cd websocketio
  - mv /Users/travis/build/tmarrinan/Build/websocketio_mac_${NODE_VERSION}.tar.gz .
  - curl -O https://bitbucket.org/tmarrinan/binary-modules/raw/master/bitbucket_upload.js
  - node bitbucket_upload.js tmarrinan $BITBUCKET_PASSWORD tmarrinan/binary-modules websocketio_mac_${NODE_VERSION}.tar.gz
  - ls -a

