version: 1.0.{build}

branches:
  only:
  - master

configuration: Release
platform: x64

#clone_depth: 5
# specific to github and bitbucket: get a ZIP file using REST API
shallow_clone: true

init:
- ps: Get-NodeJsLatestBuild 6.0

environment:
  BITBUCKET_PASSWORD:
    secure: vqHQj3wH0DrNMmmeflA6Nw==
  matrix:
  - nodejs_version: 0.10.44
  - nodejs_version: 0.12.13
  - nodejs_version: 4.4.2
  - nodejs_version: 5.10.1
  - nodejs_version: 6.0.0

install:
- ps: >-
    Install-Product node $env:nodejs_version x64

    npm -v

    node -v

    npm install --production --msvs_version=2013

build: off

#  parallel: true
#  verbosity: minimal


after_build:
- mkdir C:\Build\
- 7z a -ttar C:\Build\websocketio_win_%nodejs_version%.tar C:\projects\websocketio\
- 7z a -tgzip C:\Build\websocketio_win_%nodejs_version%.tar.gz C:\Build\websocketio_win_%nodejs_version%.tar
- move C:\Build\websocketio_win_%nodejs_version%.tar.gz C:\projects\websocketio
- curl --insecure --progress-bar --location --fail --user "renambot:%BITBUCKET_PASSWORD%" --form files=@"websocketio_win_%nodejs_version%.tar.gz" "https://api.bitbucket.org/2.0/repositories/sage2/binaries/downloads/"
- dir

test: off
