version: 1.0.{build}

image: Visual Studio 2017

branches:
  only:
  - master

configuration: Release
platform: x64

#clone_depth: 5
# specific to github and bitbucket: get a ZIP file using REST API
shallow_clone: true

init:
- ps: Get-NodeJsLatestBuild 9.4
- ps: Install-Product node 9.4.0 x64

environment:
  BITBUCKET_PASSWORD:
    secure: knMJcKTWQPaMlmpY298Z4w==
  matrix:
  - nodejs_version: 10.15.3
  - nodejs_version: 11.13.0

install:
  - ps: Install-Product node $env:nodejs_version x64
  - npm install --production --msvs_version=2017
 
build: off

test_script:
  - npm -v
  - node -v

after_test:
  - mkdir C:\Build\
  - 7z a -ttar C:\Build\websocketio_win_%nodejs_version%.tar C:\projects\websocketio\
  - 7z a -tgzip C:\Build\websocketio_win_%nodejs_version%.tar.gz C:\Build\websocketio_win_%nodejs_version%.tar
  - move C:\Build\websocketio_win_%nodejs_version%.tar.gz C:\projects\websocketio
  - curl --insecure --progress-bar --location --fail --user "renambot:%BITBUCKET_PASSWORD%" --form files=@"websocketio_win_%nodejs_version%.tar.gz" "https://api.bitbucket.org/2.0/repositories/sage2/binaries/downloads/"
  - dir
 

