version: 1.0.{build}

branches:
  only:
  - master

configuration: Release
platform: x64

#clone_depth: 5
# specific to github and bitbucket: get a ZIP file using REST API
shallow_clone: true


environment:
  BITBUCKET_PASSWORD:
    secure: ah/zb5h/z49InzWbvkFOrw==
  matrix:
  - nodejs_version: 0.10.40
  - nodejs_version: 0.12.9
  - nodejs_version: 4.2.3
  - nodejs_version: 5.1.1

install:
- ps: >-
    Install-Product node $env:nodejs_version x64

    npm -v

    node -v

    npm install --production --msvs_version=2013
- mkdir C:\Build\
- 7z a -ttar C:\Build\websocketio_win_%nodejs_version%.tar C:\projects\websocketio\
- 7z a -tgzip C:\Build\websocketio_win_%nodejs_version%.tar.gz C:\Build\websocketio_win_%nodejs_version%.tar
- move C:\Build\websocketio_win_%nodejs_version%.tar.gz C:\projects\websocketio
- curl -O https://bitbucket.org/tmarrinan/binary-modules/raw/master/bitbucket_upload.js
- node bitbucket_upload.js tmarrinan %BITBUCKET_PASSWORD% tmarrinan/binary-modules websocketio_win_%nodejs_version%.tar.gz
- dir

build: off

test: off
